### ISSUE TITLE
Linkitys olemattomaan sisällysluettelon otsikkoon rautatieliikenteen sivulla

### ISSUE THREAD

**Issue by kihyvari** [tmfg/digitraffic#5]
Kuva napattu: https://www.digitraffic.fi/rautatieliikenne/ , alleviivaus minun.

![linkki](https://user-images.githubusercontent.com/60000042/78772866-11939d80-799b-11ea-9312-3560514c27c5.jpg)

Kyseinen linkki johtaa sisällysluettelon otsikkoon #käyttöehdot, jota ei ole olemassa. Oletan, että tilalla pitäisi olla esim. #avoimen-datan-käyttölupa tai vaikkapa https://creativecommons.org/licenses/by/4.0/

**Comment by jaakko-solita** [comment]
Kiitoksia! Linkki korjattu
